theme: jekyll-theme-minimal
title: <div align="center"><img src="images/A.PNG" width="200"/></div>
description: There's a lesson here, and I'm not going to be the one to figure it out.<br /><img src="images/github.png" width="50"/>
google_analytics: UA-34006119-1